--
-- Add country codes from ISO-3166
--
BEGIN;
alter table country add column if not exists code int4;
alter table country add column if not exists code2 varchar(2);
alter table country add column if not exists code3 varchar(3);
COMMIT;

BEGIN;
update country set code = 4, code2 = 'AF', code3 = 'AFG' where country = 'Afghanistan';
update country set code = 12, code2 = 'DZ', code3 = 'DZA' where country = 'Algeria';
update country set code = 16, code2 = 'AS', code3 = 'ASM' where country = 'American Samoa';
update country set code = 24, code2 = 'AO', code3 = 'AGO' where country = 'Angola';
update country set code = 660, code2 = 'AI', code3 = 'AIA' where country = 'Anguilla';
update country set code = 032, code2 = 'AR', code3 = 'ARG' where country = 'Argentina';
update country set code = 51, code2 = 'AM', code3 = 'ARM' where country = 'Armenia';
update country set code = 36, code2 = 'AU', code3 = 'AUS' where country = 'Australia';
update country set code = 40, code2 = 'AT', code3 = 'AUT' where country = 'Austria';
update country set code = 31, code2 = 'AZ', code3 = 'AZE' where country = 'Azerbaijan';
update country set code = 48, code2 = 'BH', code3 = 'BHR' where country = 'Bahrain';
update country set code = 50, code2 = 'BD', code3 = 'BGD' where country = 'Bangladesh';
update country set code = 112, code2 = 'BY', code3 = 'BLR' where country = 'Belarus';
update country set code = 68, code2 = 'BO', code3 = 'BOL' where country = 'Bolivia';
update country set code = 76, code2 = 'BR', code3 = 'BRA' where country = 'Brazil';
update country set code = 96, code2 = 'BN', code3 = 'BRN' where country = 'Brunei';
update country set code = 100, code2 = 'BG', code3 = 'BGR' where country = 'Bulgaria';
update country set code = 116, code2 = 'KH', code3 = 'KHM' where country = 'Cambodia';
update country set code = 120, code2 = 'CM', code3 = 'CAM' where country = 'Cameroon';
update country set code = 124, code2 = 'CA', code3 = 'CAN' where country = 'Canada';
update country set code = 148, code2 = 'TD', code3 = 'TCD' where country = 'Chad';
update country set code = 152, code2 = 'CL', code3 = 'CHL' where country = 'Chile';
update country set code = 156, code2 = 'CN', code3 = 'CHN' where country = 'China';
update country set code = 170, code2 = 'CO', code3 = 'COL' where country = 'Colombia';
update country set code = 180, code2 = 'CD', code3 = 'COD' where country = 'Congo, The Democratic Republic of the';
update country set code = 203, code2 = 'CZ', code3 = 'CZE' where country = 'Czech Republic';
update country set code = 214, code2 = 'DO', code3 = 'DOM' where country = 'Dominican Republic';
update country set code = 218, code2 = 'EC', code3 = 'ECU' where country = 'Ecuador';
update country set code = 818, code2 = 'EG', code3 = 'EGY' where country = 'Egypt';
update country set code = 233, code2 = 'EE', code3 = 'EST' where country = 'Estonia';
update country set code = 231, code2 = 'ET', code3 = 'ETH' where country = 'Ethiopia';
update country set code = 234, code2 = 'FO', code3 = 'FRO' where country = 'Faroe Islands';
update country set code = 246, code2 = 'FI', code3 = 'FIN' where country = 'Finland';
update country set code = 250, code2 = 'FR', code3 = 'FRA' where country = 'France';
update country set code = 254, code2 = 'GF', code3 = 'GUF' where country = 'French Guiana';
update country set code = 258, code2 = 'PF', code3 = 'PYF' where country = 'French Polynesia';
update country set code = 270, code2 = 'GM', code3 = 'GMB' where country = 'Gambia';
update country set code = 276, code2 = 'DE', code3 = 'DEU' where country = 'Germany';
update country set code = 300, code2 = 'GR', code3 = 'GRC' where country = 'Greece';
update country set code = 304, code2 = 'GL', code3 = 'GRL' where country = 'Greenland';
update country set code = 336, code2 = 'VA', code3 = 'VAT' where country = 'Holy See (Vatican City State)';
update country set code = 344, code2 = 'HK', code3 = 'HKG' where country = 'Hong Kong';
update country set code = 348, code2 = 'HU', code3 = 'HUN' where country = 'Hungary';
update country set code = 356, code2 = 'IN', code3 = 'IND' where country = 'India';
update country set code = 360, code2 = 'ID', code3 = 'IDN' where country = 'Indonesia';
update country set code = 364, code2 = 'IR', code3 = 'IRN' where country = 'Iran';
update country set code = 368, code2 = 'IQ', code3 = 'IRQ' where country = 'Iraq';
update country set code = 376, code2 = 'IL', code3 = 'ISR' where country = 'Israel';
update country set code = 380, code2 = 'IT', code3 = 'ITA' where country = 'Italy';
update country set code = 392, code2 = 'JP', code3 = 'JPN' where country = 'Japan';
update country set code = 398, code2 = 'KZ', code3 = 'KAZ' where country = 'Kazakstan';
update country set code = 404, code2 = 'KE', code3 = 'KEN' where country = 'Kenya';
update country set code = 414, code2 = 'KW', code3 = 'KWT' where country = 'Kuwait';
update country set code = 428, code2 = 'LV', code3 = 'LVA' where country = 'Latvia';
update country set code = 438, code2 = 'LI', code3 = 'LIE' where country = 'Liechtenstein';
update country set code = 440, code2 = 'LT', code3 = 'LTU' where country = 'Lithuania';
update country set code = 450, code2 = 'MG', code3 = 'MDG' where country = 'Madagascar';
update country set code = 454, code2 = 'MW', code3 = 'MWI' where country = 'Malawi';
update country set code = 458, code2 = 'MY', code3 = 'MYS' where country = 'Malaysia';
update country set code = 484, code2 = 'MX', code3 = 'MEX' where country = 'Mexico';
update country set code = 498, code2 = 'MD', code3 = 'MDA' where country = 'Moldova';
update country set code = 504, code2 = 'MA', code3 = 'MAR' where country = 'Morocco';
update country set code = 508, code2 = 'MZ', code3 = 'MOZ' where country = 'Mozambique';
update country set code = 104, code2 = 'MM', code3 = 'MMR' where country = 'Myanmar';
update country set code = 520, code2 = 'NR', code3 = 'NRU' where country = 'Nauru';
update country set code = 524, code2 = 'NP', code3 = 'NPL' where country = 'Nepal';
update country set code = 528, code2 = 'NL', code3 = 'NLD' where country = 'Netherlands';
update country set code = 554, code2 = 'NZ', code3 = 'NZL' where country = 'New Zealand';
update country set code = 566, code2 = 'NG', code3 = 'NGA' where country = 'Nigeria';
update country set code = 408, code2 = 'KP', code3 = 'PRK' where country = 'North Korea';
update country set code = 512, code2 = 'OM', code3 = 'OMN' where country = 'Oman';
update country set code = 586, code2 = 'PK', code3 = 'PAK' where country = 'Pakistan';
update country set code = 600, code2 = 'PY', code3 = 'PRY' where country = 'Paraguay';
update country set code = 604, code2 = 'PE', code3 = 'PER' where country = 'Peru';
update country set code = 608, code2 = 'PH', code3 = 'PHL' where country = 'Philippines';
update country set code = 616, code2 = 'PL', code3 = 'POL' where country = 'Poland';
update country set code = 630, code2 = 'PR', code3 = 'PRI' where country = 'Puerto Rico';
update country set code = 642, code2 = 'RO', code3 = 'ROU' where country = 'Romania';
update country set code = 638, code2 = 'RE', code3 = 'REU' where country = 'Runion';
update country set code = 643, code2 = 'RU', code3 = 'RUS' where country = 'Russian Federation';
update country set code = 670, code2 = 'VC', code3 = 'VCT' where country = 'Saint Vincent and the Grenadines';
update country set code = 682, code2 = 'SA', code3 = 'SAU' where country = 'Saudi Arabia';
update country set code = 686, code2 = 'SN', code3 = 'SEN' where country = 'Senegal';
update country set code = 703, code2 = 'SK', code3 = 'SVK' where country = 'Slovakia';
update country set code = 710, code2 = 'ZA', code3 = 'ZAF' where country = 'South Africa';
update country set code = 410, code2 = 'KR', code3 = 'KOR' where country = 'South Korea';
update country set code = 724, code2 = 'ES', code3 = 'ESP' where country = 'Spain';
update country set code = 144, code2 = 'LK', code3 = 'LKA' where country = 'Sri Lanka';
update country set code = 729, code2 = 'SD', code3 = 'SDN' where country = 'Sudan';
update country set code = 752, code2 = 'SE', code3 = 'SWE' where country = 'Sweden';
update country set code = 756, code2 = 'CH', code3 = 'CHE' where country = 'Switzerland';
update country set code = 158, code2 = 'TW', code3 = 'TWN' where country = 'Taiwan';
update country set code = 834, code2 = 'TZ', code3 = 'TZA' where country = 'Tanzania';
update country set code = 764, code2 = 'TH', code3 = 'THA' where country = 'Thailand';
update country set code = 776, code2 = 'TO', code3 = 'TON' where country = 'Tonga';
update country set code = 788, code2 = 'TN', code3 = 'TUN' where country = 'Tunisia';
update country set code = 792, code2 = 'TR', code3 = 'TUR' where country = 'Turkey';
update country set code = 795, code2 = 'TM', code3 = 'TKM' where country = 'Turkmenistan';
update country set code = 798, code2 = 'TV', code3 = 'TUV' where country = 'Tuvalu';
update country set code = 804, code2 = 'UA', code3 = 'UKR' where country = 'Ukraine';
update country set code = 784, code2 = 'AE', code3 = 'ARE' where country = 'United Arab Emirates';
update country set code = 826, code2 = 'GB', code3 = 'GBR' where country = 'United Kingdom';
update country set code = 840, code2 = 'US', code3 = 'USA' where country = 'United States';
update country set code = 862, code2 = 'VE', code3 = 'VEN' where country = 'Venezuela';
update country set code = 704, code2 = 'VN', code3 = 'VNM' where country = 'Vietnam';
update country set code = 850, code2 = 'VI', code3 = 'VIR' where country = 'Virgin Islands, U.S.';
update country set code = 887, code2 = 'YE', code3 = 'YEM' where country = 'Yemen';
update country set code = 894, code2 = 'ZM', code3 = 'ZMB' where country = 'Zambia';
COMMIT;

-- create unique index code;
-- create unique index code2;
-- create unique index code3;

